### ISSUE TITLE
Modify path

### ISSUE THREAD

**Issue by backflip** [amwmedia/plop#107]
If I'm interpreting https://github.com/amwmedia/node-plop/blob/master/src/actions/modify.js#L25-L28 correctly, the `modify` action does not allow to change the path. Is there a recommendation for moving/renaming files while modifying them? I'm currently relying on a custom action with Gulp for this since I'm using it in other places anyway, but I'm not sure whether there would be a better solution:

```js
return [
  new Promise((resolve) => {
    gulp.src(/* Read files */)
      .pipe(/* Manipulate paths */)
      .pipe(gulp.dest(/* Write to new location */))
      .on('end', () => {
        del(/* Delete original files */).then(() => resolve());
      });
  }),
];
```

**Comment by amwmedia** [comment]
Currently a custom action would be the way to go for this. Maybe if you could explain your use case a little more, another solution might come to mind? I'm having trouble understanding why you would want to "modify and move" some files around your codebase.

**Comment by backflip** [comment]
It’s mostly about renaming components. For this they need to be moved as well as slightly refactored (renaming of class names etc.).

**Comment by backflip** [comment]
The class renaming could be taken care of by a capable IDE though.

**Comment by amwmedia** [comment]
Are you building a one time script to mass refactor a codebase? Like something you might use jscodeshift for?

**Comment by backflip** [comment]
It’s only about occasional renaming of single components. But thanks for pointing out jscodeshift, I’ll have a look!

**Comment by amwmedia** [comment]
What I have personally done for renaming a component, is just `plop` a new component with the name I want and copy the file contents from the old to the new. Reversing what the template does so you can rename `component-a` to `component-b` can be brittle because it joins those 2 generators at the hip so that a change to one requires a change to the other.

All that said, if you wanted to build a `rename` action, it would be pretty straight forward to make your own [`actionType`](https://plopjs.com/documentation/#setactiontype) or [custom action function](https://plopjs.com/documentation/#custom-action-function-) that did what you want.
