### ISSUE TITLE
{{{ triple brackets freak out handlebars

### ISSUE THREAD

**Issue by gabrielcrowe** [amwmedia/plop#116]
in typescript when i'm adding a controller to my project i find that plop has a wobbly when adding something with thee curlys, for example:

template: '$1\r\nimport {{{properCase noun}}Controller} from \'../endpoint/{{dashCase noun}}\';'
__________________________^

I can cheat this by putting a space after the first curly, but then it looks terribad in the code. Can we disable triples? HTML-escapes aren't really useful for this type of text wrangling anyhow. :)

**Comment by amwmedia** [comment]
ah, yes, working with files that need legitimate curly braces can be a little weird because of the clash in template syntax with handlebars. There has been some work toward making plop able to support different template engines, but that is not available at the moment. If you don't like adding some extra space between the curly and text, you can work around this with helpers. For the template you are constructing you could use a helper like...
```
plop.setHelper('preCurly', t => `{${t}`);
```
... and modify your code to be something like...
```
import {{preCurly (properCase noun)}}Controller} from '../endpoint/{{dashCase noun}}';
```
Hope that helps.
