### ISSUE TITLE
Is it possible for API request and write response a variable to be available to use within template files?

### ISSUE THREAD

**Issue by nuri-engin** [amwmedia/plop#124]
I hope that the title is explain whole situation;

I need something like; 

```
// in plopfile.js
fetch('http://example.com/movies')
  .then(function(response) {
    return response.json();
  })
  .then(function(myJson) {
    console.log(myJson);
  });

//Here I need to set `myJson` to be a plop-variable to be able for usage in plop-templates. 
```

and then I need to set `myJson` response to variable and using this response of JSON within a `ExtJS` `model` class.

```
// FooModel.js
   Ext.define(MyApp.Model, {
   fields: [
            {{myJsonVariable}} //Here I'll use the request response.
   ] 
...
});
```

**Comment by nuri-engin** [comment]
Hello dear @amwmedia .. Is there any kind of advice you can offer?

**Comment by amwmedia** [comment]
you can use a [customAction](https://plopjs.com/documentation/#custom-action-function-) function to make the request and augment the answer data for the rest of the actions to use. This approach is currently broken, but should be fixed in the next version of plop which I'm getting ready to push out.

I am also pushing a change to the `data` property on all [actionConfig](https://plopjs.com/documentation/#interface-actionconfig) objects that will allow you to supply a function that returns a data object or a Promise that resolves with a data object. This will also be in the next version of plop.
