### ISSUE TITLE
Adding custom messaging during action steps

### ISSUE THREAD

**Issue by handonam** [amwmedia/plop#125]
I wanted to try to add documentation for my new developers to explain what files are being added/modified during the action step. What i'm looking to have is this:

```
Adding necessary configuration files:
[SUCCESS] add <path>
[SUCCESS] add <path>

Modify your contents here:
[SUCCESS] add <path>
[SUCCESS] add <path>

Updating some other things you don't need to touch:
[SUCCESS] modify <path>
```

I was attempting to use the customActions for this, but it would print messages like this:
```
[SUCCESS] function Adding necessary configuration files:
[SUCCESS] add <path>
[SUCCESS] add <path>
```

Any thoughts on what I could do here?

**Comment by amwmedia** [comment]
I think at the very least, it would make sense to remove the `function` prefix that gets added to the customActionFunction message. 👍

**Comment by hamzazaidi** [comment]
@amwmedia I am going  to take a look into this.

**Comment by amwmedia** [comment]
You know, I was just thinking... what if we added the ability to just put strings into the actions array? So a list of actions could include strings instead of objects that would be pushed to the screen as the actions are run. That could provide some valuable documentation for what new new files are and how to they should be used.

**Comment by hamzazaidi** [comment]
I think it is a great idea, description property can be added to explain the purpose of the action. 
If description property is added what is going to be the default where the property is specified.

**Comment by williamdclt** [comment]
I'd need something like that too, and a custom action fits my needs (I just skip a line for a bit more clarity). My problem is that some of my action take a while to finish but all the logging is batched to the end. That means that the user has no feedback of anything that's happening until all actions have finished, is there a way around that?

**Comment by amwmedia** [comment]
Thanks for the input. Sorry for the delay, I've been out of town for the last week. 

I'd be open to either option here. I'm a little partial to the callback approach because it's very simple to understand, though I agree with your sentiment that _this is kind of what generators are designed to do_. I would only be concerned that the resulting code might not be quite as maintainable, but I'm willing to be proved wrong. 🙂

Overall, I think making the logging asynchronous is important, especially because custom action functions can return a Promise and take as long as they need.

We could also bring in something like [`ora`](https://github.com/sindresorhus/ora) to polish up the output experience.

**Comment by gregglind** [comment]
Templating from `answers` would be nice to have.  I solved it this way:

```
        function thingCreated (answers) {
            const msg = 'thing created at {{place}}/{{id}}/';
            return plop.renderString(msg, answers);
        }
```

Pure strings are also nice.  Perhaps pure strings could always be assumed to run through plot.renderString?

**Comment by amwmedia** [comment]
Great call out! I'll definitely make sure that's added in.

**Comment by amwmedia** [comment]
[released](https://plopjs.com/documentation/#comments) in v2.2.0
