### ISSUE TITLE
Setting --plopfile and --cwd doesn't forward the cwd

### ISSUE THREAD

**Issue by etatarevic** [amwmedia/plop#136]
Correct me if I am wrong here, but if I try to run something like 
`plop --plopfile 'LOCATION' --cwd 'CURR_LOCATION'` 
the current working location does not get passed along to node-plop. 

Around line 68 in plop.js it should pass "force" and "destBasePath" into the nodePlop constructor. 

It should look something like this 
`// set the default base path to the plopfile directory
	const plop = nodePlop(plopfilePath, {
		force: argv.force || argv.f,
		destBasePath: argv.cwd
	});`

**Comment by amwmedia** [comment]
Interesting idea. I never intended for the cwd to be used as the destination path. Plop has always used the location of the plopfile as the base path for all generated files and locating templates. I can see why the presence of the cwd arg would lead you that direction though.

Can you provide a description of how you would envision this working? Do you want to generate code based on where you are in the codebase?

**Comment by etatarevic** [comment]
The reason I needed this is I want plop to write the necessary files to where the command was ran from while finding the plopfile in a completely different place.

This is so that our users can install the plop generator repo once, globally, and then run a command from anywhere and plop will put all the files it needs to in the path that they ran the command from.

**Comment by amwmedia** [comment]
So, 2 things that I think could help you.

1. [`plop.load()`](https://github.com/amwmedia/plop/blob/master/plop-load.md) allows you to pull assets (generators, helpers, etc) from another plopfile by path OR via an NPM package (installed globally or locally).
2. you can [create a helper](https://github.com/amwmedia/plop/issues/68) that accesses the `cwd` and use it when defining paths for your files.

**Comment by amwmedia** [comment]
but what you are describing sounds more inline with what we are planning to do with [project scaffolding](https://github.com/amwmedia/plop/issues/51).

**Comment by etatarevic** [comment]
I'll look into that, but I am curious, why not implement the nodePlop constructor fully with force parameter and destBasePath parameter?

**Comment by amwmedia** [comment]
`force` works as expected, however `cwd` is a bit of a weird one because "current working directory" does exactly mean "target directory". I can understand why there was confusion about it, and honestly the `cwd` prop should probably have not been added in the first place because it's unclear what it would do.

It does seem that there's a desire to have generators that use the current working directory as the base path for generation, but I'm not sure of the best way to provide that kind of feature without making things confusing for the user. If I run a generator, I expect it to know where to put the assets. Most plop generators are used to generate new assets in an existing structure, so things aren't really relative to where in the project I happen to be.
