### ISSUE TITLE
Best way to create a wizard using plop and npm init?

### ISSUE THREAD

**Issue by pdehaan** [amwmedia/plop#137]
We're trying to create a wizard for creating new modules (similar to create-react-app) but I'm a bit confused how to best use plop.

Our ideal flow would be something like <kbd>$ npm init foo</kbd> which would invoke the **create-foo** module in npm, but I'm struggling to see how we can use **plop** and/or **node-plop**.

We have a prototype which uses plop, but it is invoking plop via Bash (which isn't ideal):

```sh
#!/bin/bash

./node_modules/.bin/plop --plopfile plop-shield-study.js $@
```

We also had an interation which uses **node-plop**, but were curious if there was an easier way:

```js
// index.js
const nodePlop = require('node-plop');
const plop = nodePlop('./plop-shield-study.js');
const basicAdd = plop.getGenerator('controller');

async function main() {
  try {
    const prompts = await basicAdd.runPrompts();
    const results = await basicAdd.runActions(prompts);
    console.log(results);
  } catch (err) {
    console.error(err);
  }
}

main();
```

I wasn't sure if there were any docs or guidance on using **plop** w/ `npm init` (see: https://elijahmanor.com/npm-init-initializer/)

**Comment by amwmedia** [comment]
Yes, it looks like you've pretty much landed on the solution. If you want to use `plop` instead of `node-plop` it would be possible by mutating `process.argv` to be what `plop` would expect, and then using `require('plop')` to kick of the execution. I've seen other people use this method to basically create a project scaffolder that uses `plop` behind the scenes.

Using `node-plop` is the more correct way to do this, but it means you have to do your own CLI layer on top and don't benefit from what `plop` already has in place.
