### ISSUE TITLE
Plop without CLI or global installation

### ISSUE THREAD

**Issue by VladimirHumeniuk** [amwmedia/plop#146]
Is it possible to run plop generators without CLI? For example, i want to create my own cli with plop for generate files, and i can't ask my users to install Plop as global dependency. 

Is it possible, to run generator without having installed plop in global? Or maybe i can just import Plop to my own js files as module, and run it in this way?

Thanks.

**Comment by indrekpaas** [comment]
Hi @VladimirHumeniuk, I experienced a similar issue recently where I wanted to run plop generators with `npx` instead of having to install them globally first.

I'll share my basic setup, which should be easy to adjust to every need.

## Project structure

```
awesome-generator/
├── index.js
├── package.json
└── plopfile.js
```

### `package.json`

* Add `plop` dependency.
* Add `bin` field and point it to `index.js`. This file will be executed when the project is run with `npx`.
* Optionally, add `execa` dependency for simpler `child_process` management in Node.

```json
{
  "name": "awesome-generator",
  "version": "0.1.0",
  "bin": "index.js",
  "dependencies": {
    "execa": "^1.0.0",
    "plop": "^2.2.0"
  }
}
```

### `index.js`

* Update file permissions with `chmod +x index.js` to make it executable.
* Add node shebang on the first line. It will allow this file to be executed from the command line.

```js
#!/usr/bin/env node

const execa = require('execa');

(async () => {
  const { stdout } = await execa('plop', { stdio: 'inherit' });
})();
```

### `plopfile.js`

This is your standard plopfile.

## Usage

Before you can start using your generators with `npx` you need to publish them on `npm`.

Once you have, you can run your generators everywhere with `npx awesome-generator` without having to install it globally.

Let me know if you have questions.

Cheers

**Comment by amwmedia** [comment]
Yes, you have 2 options here.

1. **The easy way:** You can use plop directly by altering argv before using `require()` to start it up. Others have used [this method](https://github.com/amwmedia/plop/issues/137) previously.
2. **The in-depth way:** You can use [node-plop](https://github.com/amwmedia/node-plop) to really customize the experience. Node-plop is what does all the work under the covers for the plop CLI. There's no official documentation, but there are some TypeScript definitions, and the API is very similar to the standard plop API (with a few additions).
