### ISSUE TITLE
Forcing the creation of files

### ISSUE THREAD

**Issue by brock** [amwmedia/plop#16]
I'd like to be able to run a plopfile add action and overwrite the existing files. I've tried setting `abortOnFail` to false without any luck. I imagine I can delete the existing files in my custom action, but am curious if there is already a built-in way to do this. I couldn't find docs for `abortOnFail`.

Edit: this is specifically for use with the add function.

**Comment by amwmedia** [comment]
yes, i need to add some documentation to the README about abortOnFail. Basically, if true, is says "if this step fails, don't execute anything further, just fail everything because I failed."

To answer your question. I suppose you could use a modify task and have the regex select the entire contents of the file for replacement. I've never personally tried it, but it should work. 

I wouldn't want to make overwriting the default behavior because I've often tried to plop a service or helper and had it fail because someone else had already created a service with that name. I would NOT want my mistake to replace their service with a blank one. :-)
