### ISSUE TITLE
Confirm before generating

### ISSUE THREAD

**Issue by dogoku** [amwmedia/plop#163]
Hi, is it possible to provide a confirm message before generating and ideally, provide a list of what changes will be made (same list you get after generate currently)?

Thanks

**Comment by amwmedia** [comment]
it's not currently possible (at least not easily) because actions can include arbitrary code that the generator runs. This code can perform all sorts of functions that plop won't know about.

I've looked in the past for something that would mock the `fs` module similar to something like [mock-fs](https://github.com/tschaub/mock-fs) to keep track of all changes being made by the actions. Then you could re-run or "flush" the changes to the actual file system. However, I'm not aware of a module that currently does this.
