### ISSUE TITLE
global help menu

### ISSUE THREAD

**Issue by brock** [amwmedia/plop#2]
Really digging this repo @amwmedia The final paragraph of the README is spot on. Some thoughts:

Since I'm installing this globally, there are a few things that could be really handy...

* `plop help` or `plop --help`
* `plog init` to generate a simple `plopfile.js` in a directory. I'd envision this with some boilerplate like the `addHelper` and `setGenerator`.

If you have any opinions on how that would be implemented, I'd be happy to submit a pull request. Really excited to start using this though. Cheers!

**Comment by amwmedia** [comment]
Hey Brock (love that name BTW), 

I think plop could probably benefit from an init option. And I think having an init option would probably make the help option more important. I think we'd need to use `--help` because `plop help` with the current setup would look for a generator called "help". Though I suppose the code could simply show the help screen for `plop help` if it fails to find a help generator (which will be the case 90% of the time).

I've been able to get by without these so far mostly because the CLI is so basic. There's really not much to explain at this point... just type `plop` and you're good to go. If you wanted to look into [commander](https://github.com/tj/commander.js) for this, that would probably fit the bill. I've been meaning to research it myself. If you'd like to fork and start a branch to get a basic --help option in place, I think that'd be a great place to start. Then once we have --help in place, we can look into how to best implement a plop init option.

Thoughts?

**Comment by brock** [comment]
sounds good. I've got something started that we can play around with, but it is still buggy. It isn't ready for a pull request yet, but here is the branch if you'd like to have a look.

https://github.com/brock/plop/tree/help

**Comment by brock** [comment]
Okay, I think I've got a good working version now, so I'm going to open a pull request. Having said that, I was really just plowing through towards a working version, so it might help to have other folks take a look at this since commander is essentially taking over the logic, and there may still be some refactoring we could do. A job for tomorrow. :)

**Comment by amwmedia** [comment]
Thanks! I'll try to take a look at this soon.

**Comment by amwmedia** [comment]
i think the ideal would be something like:

 - plop would bring up the list of generators if a plopfile is found, otherwise the "no plopfile found" message and help
 - plop -h or plop --help would bring up the help menu
 - plop -i or plop --init would kick off an inquirer based process that would generate a plopfile in the current directory. This process would allow the developer to select what should be included. Examples would be things like "helper function", "add action", "modify action", "custom action function (sync)", "custom action function (async)", etc.
 - plop -v or plop --version would print the current version
 - plop _anythingElse_ would try to launch that generator. If no generator by that name is found, the error is shown along with the help screen.

thoughts?
