### ISSUE TITLE
Download template from github/git repo?

### ISSUE THREAD

**Issue by davidtaboas** [amwmedia/plop#20]
It's possible get the templates from a git repository?

**Comment by amwmedia** [comment]
is your main goal to have multiple projects use the same plop generators and templates? If so I think @nicksrandall was doing this by publishing them as an npm module. Maybe he would be kind enough to share how that approach worked for him :smile:

**Comment by nicksrandall** [comment]
@davidtaboas Sorry for the delayed response. Yes, I did this by publishing my plop code as a (private) npm module. Then in each of my projects, my `plopfile.js` looks something like this:

```js
module.exports = require('my-plops');
```

and that's it!

**Comment by amwmedia** [comment]
@davidtaboas the short answer to your question is no, plop doesn't support dynamically downloading templates when you trigger plop. However if you're looking to centralize your generators for use on multiple projects, there's a pretty nice solution to be had with npm ;-)

**Comment by calcaide** [comment]
@nicksrandall Thanks for that idea, actually I made two plop generators ([plop-react-webpack](https://www.npmjs.com/package/plop-react-webpack) and [plop-node-express](https://www.npmjs.com/package/plop-node-express)) with that approach and works pretty well.

Just note, that in the generator `plopfile.js`, in all `templateFile` property I had to writte the route like that `node_modules/plop-node-express/....` is that correct? I mean, another way to do it? Thanks in advance.

**Comment by amwmedia** [comment]
@calcaide I believe right now this is the way you would do this. However, soon I'll be adding in full support for these types of approaches. The way I'm planning to do this would allow your shared plopfiles to reference everything locally like they normally would, but give the consumer plopfile control to specify where the generated files should be placed. still working out the details, but this is sort of the "next" thing on my agenda for plop after I get it integrated with [node-plop](https://github.com/amwmedia/node-plop)

**Comment by calcaide** [comment]
@amwmedia Many thanks for the answer. The [node-plop](https://github.com/amwmedia/node-plop) looks pretty cool, are you accepting contributors? Because I am interested in contribute to the project. Since I meet plop (a few weeks ago) I really fall in love with, I think is very much simpler than Yeoman. Actually, I am using Plop as a generator (replacing yeoman) and as micro-generator. Thank you for make Plop

**Comment by amwmedia** [comment]
@calcaide really glad you like plop and are having good success with it. I'm always open to ideas and contributions! I would just ask that if you have an idea for a new feature, start the conversation as an **issue** so we can brainstorm and layout a plan for implementation. 

Things that are ready to be worked on are the integration work so that `plop` is using `node-plop` internally and documentation for `node-plop`. Let me know how you'd like to be involved. I'm actually planning to take on this feature (sharable modules) next within node-plop... after I finish up the additional test coverage that I'm wrapping up now.

**Comment by calcaide** [comment]
@amwmedia  ok, you are right. I thing start the conversation as an issue is perfect. I will do that to not pollute more this issue. My intention is start contributing with little things and ideas.
