### ISSUE TITLE
May be create a more "shareable" ecosystem for plop?

### ISSUE THREAD

**Issue by kevin-wolf** [amwmedia/plop#23]
I just met plop. And I am _in love_ with it.

**Why I choose Plop over Yeoman**?
Because it is composable, I can set a project by calling some third party _plops_ (#20) and also add my owns, right on this way:

``` js
module.exports = function (plop) {
  require('plop-generator-react')(plop);
  require('plop-generator-redux')(plop);

  // Custom generators here...
};
```

So my proposal is: why not creating a website for Plop? And may be list the community created Plops?

Cheers :).

**Comment by mxstbr** [comment]
:+1: I agree, plop is awesome and this would greatly help make it seem more professional and polished.

We're going to use it for [react-boilerplate v3](https://github.com/mxstbr/react-boilerplate/tree/v3.0.0), and I'd love to showcase it a bit in the documentation because I think it's awesome.

**Comment by amwmedia** [comment]
Agreed! I've been thinking about how best to do something like this. The main challenge is finding a way to do it that preserves the simplicity and customizability of plop. Maybe just being able to modify the generators in your own code after they are required is enough. So if the `required` generator has a `path` of `/app/components/{{ camelCase name }}.js`, you would be able to change that to match your project preference.

Thoughts?

Thanks for your input @mxstbr and @kevin-wolf. :smile:

**Comment by mxstbr** [comment]
Maybe making `setGenerator` return a callback that accepts options would make usage nice, something like this:

```JS
module.exports = (plop) => {
  plop.setGenerator('component', (options) => {
    const componentPath = options.componentPath || 'default/componentPath';

    return {
      description: 'bla',
      prompts: [],
      actions: (data) => {
        return [{
          type: 'add',
          path: componentPath,
          templateFile: 'someTemplate.hbs'
        }]
      },
    }
  }
};
```

which would allow you to use it like this to pass your desired path for the component generator like so:

```JS
require('plop-generator-react')({
  componentPath: 'bla/{{ properCase name }}/index.js'
})
```

This is a very flexible solution, as generator authors could have you customize everything they want you to customize, since they dictate which options they accept and which one's they don't accept.

**Comment by kevin-wolf** [comment]
Or may be a way to set configuration into the `plop` object, something like this:

```javascript
module.exports = function (plop) {
  plop.configs = {}; // All your configs.

  require('plop-generator-react')(plop);
  require('plop-generator-redux')(plop);
};

**Comment by mxstbr** [comment]
Yeah that could work too and would probably require less rewriting!

**Comment by amwmedia** [comment]
I think a combination of the 2 might work out nicely. What if we changed the plopfile interface to optionally accept a config object for that file? In the case of shared generators, they could be developed and distributed in a more granular fashion which would allow users to mix and match. Then each module developer could create their own interface for that config file and basically provide a way to customize the functionality.

*so a module would look something like this...*
```javascript
module.exports = function (plop, config) {
    var configDefaults = {basePath: 'src/modules'};
    var cfg = Object.assign({}, configDefaults, config);
    plop.setGenerator('basics', {
        description: 'this is a skeleton plopfile',
        prompts: [...],
        actions: [{
            type: 'add',
            path: cfg.basePath + '/something.js',
            ...etc
        }]
    });
};
```

*and would be used like this...*
```javascript
module.exports = function (plop) {
    require('plop-generator-react')(plop, {basePath: 'app/mods'});
    require('plop-generator-redux')(plop, {basePath: 'app/models'});
};
```

actually, now that I look at this, I believe this would even work _today_. The only work would be to build the site and solidify the approach so that everyone knows what to expect from shared generators. :smile: I haven't tested it, but I don't believe this would even require a refactor.

**Comment by amwmedia** [comment]
this is finally complete, take a look at [plop.load](https://github.com/amwmedia/plop/blob/master/plop-load.md). Also you can look at the very basic code for [the `plop-pack` I published](https://github.com/amwmedia/plop-pack-fancy-comments/blob/master/index.js) in order to test this all out.

**Comment by amwmedia** [comment]
The first version of the website is finally out there. No list of community plop assets yet, but it's definitely on the radar. http://plopjs.com
