### ISSUE TITLE
Add PWD option for `path`

### ISSUE THREAD

**Issue by kentcdodds** [amwmedia/plop#5]
Maybe this is possible but after looking at the docs and some of the code I don't think so. I want to be able to navigate to a folder and generate some files there rather than having the `path` be relative to the `plopfile.js` file, I'd rather have the `path` be relative to where the command is executed. Right now, I can accomplish this by generating the `path` like this:

```javascript
function getPath(subPath) {
  const plopPath = process.cwd().substring(plop.getPlopfilePath().length + 1)
  return path.join(plopPath, subPath)
}
```

But I'd much rather not have to do that and do this instead:

```javascript
{
  type: 'add',
  path: '{{name}}.js',
  usePWDForPath: true,
  // ...etc
}
```

An important note here is that the `templateFile` should remain as it is and should not be relative to the `PWD`.

What do you think?

**Comment by amwmedia** [comment]
Hey Kent, interesting idea. What is the use case where you believe this would be especially useful? In every case I've come across so far, I've found it better to build the generator so that everything it needs to execute comes from the questions asked. That way the developer doesn't need to know whether or not the CWD is important for THIS generator vs another one.

This would technically be pretty simple to do through a helper though. If you used the code you wrote above as a helper function you could declare it once at the top and reuse it in all of your paths and templates...

``` javascript
{
  type: 'add',
  path: '{{pwd name}}.js'
  // ...etc
}
```

If there's enough value in a helper like this, it could easily be built into the baked in helpers.

**Comment by kentcdodds** [comment]
I like the helper idea. I understand what you mean by allowing the user to provide everything that's needed for the generator. Is there a way with the prompts to provide default values? In that scenario, I could prompt the user for the path they'd like but have it default to the current working directory. I think I'd be happy with that solution if it's possible :-)

**Comment by kentcdodds** [comment]
Looks like that's possible. I'll close this for now. Thanks! https://www.npmjs.com/package/inquirer#question

**Comment by bsr203** [comment]
hi @kentcdodds I too like to have this behavior and is there any of your public repo contains this implementation? else, can you please share the snippets to enable this?

**Comment by kentcdodds** [comment]
Unfortunately no, and I no longer have access to that repo. But @TheMcMurder does. Maybe he'd be willing to share a code snippet.

**Comment by bsr203** [comment]
thanks @kentcdodds for quick response

**Comment by amwmedia** [comment]
@bsr203 you might want to take a look at [inquierer-directory](https://github.com/nicksrandall/inquirer-directory) by @nicksrandall. it doesn't do exactly this, but it's a very nice way to pick a specific directory
