### ISSUE TITLE
Fixed path for templates 

### ISSUE THREAD

**Issue by NetanelBasal** [amwmedia/plop#79]
Hey, first of all, I would like to say thank you for this library. I released a [generator](https://github.com/NetanelBasal/ngrx-generator/) this week that built with plop. 

I have a question related to a [feature](https://github.com/NetanelBasal/ngrx-generator/issues/1) they asked me to add.
Is it possible to set a fixed path where the templates will be created, no matter what folder I am in?

Thanks.

**Comment by amwmedia** [comment]
The path value for the `add` action can be relative or static. If it's relative, then the base directory is the plopfile path. I see that this won't help you because your generator is installed as a standalone binary.

So I suppose one way you could do this would be to have an optional property people can add to their package.json file that would define the static base path for the generator to use. You could then use something like [findUp](https://www.npmjs.com/package/find-up) to locate the package.json that is upstream from their current working directory. I would think all of this logic could be wrapped up into some sort of helper.

**Comment by NetanelBasal** [comment]
Yes, I thought about that, too. I just thought there might be a built-in way. Thanks anyway, keep up the good work. 👍

**Comment by amwmedia** [comment]
Thanks! 👍 

If you were using [node-plop](https://github.com/amwmedia/node-plop) you could define a `baseDestPath` property when you first instantiated the code. However, I realize that `node-plop` is not yet fully documented, and there's a lot of benefit to just firing up the plop CLI. Good luck!
