### ISSUE TITLE
Support file overwrite

### ISSUE THREAD

**Issue by kentcdodds** [amwmedia/plop#90]
With yeoman, if there's a file already in place and you want to write a file there, it will ask the user if they'd like to overwrite it. Is that a feature plop could have?

**Comment by amwmedia** [comment]
It is certainly a possibility. I haven't seen it as a high priority so far because it seems to me that 90% of the time if my generator is going to overwrite something that is pre-existing, it means I need to backup and provide different input. Can you think of a real-world scenario where you'd want to actually overwrite?

**Comment by amwmedia** [comment]
this is a duplicate of #32.
